sudo: false
language: python

cache:
  directories:
    - .benchmarks
branches:
  only:
    - master

before_install:
  - pip install --upgrade pip setuptools wheel

matrix:
  include:
  - os: linux
    env: NAME=mypy
    python: "3.6"
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep mypy | xargs pip install
    script: check/mypy

  - os: linux
    env: NAME=pylint
    python: "3.6"
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep "pylint\|astroid" | grep -v "#" | xargs pip install
    script: check/pylint

  - os: linux
    env: NAME=format
    python: "3.6"
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep yapf | xargs pip install
    script: check/format-incremental

  - os: linux
    env: NAME=pytest-and-incremental-coverage
    python: "3.6"
    install:
      - pip install -r requirements.txt
      - pip install -r cirq/contrib/contrib-requirements.txt
      - pip install -r dev_tools/conf/pip-list-dev-tools.txt
    script: check/pytest-and-incremental-coverage master --actually-quiet

  - os: linux
    env: NAME=pytest (without contrib)
    python: "3.7"
    install:
      - pip install -r requirements.txt
      - pip install -r dev_tools/conf/pip-list-dev-tools.txt
    script: check/pytest --ignore=cirq/contrib --benchmark-skip --actually-quiet

  - os: windows
    env: NAME=pytest (Windows)
    language: sh
    python: "3.7.3"
    before_install:
    - powershell -command 'Set-MpPreference -DisableArchiveScanning $true'
    - powershell -command 'Set-MpPreference -DisableBehaviorMonitoring $true'
    - powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
    - choco install python --version 3.7.3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - python -m pip install --upgrade pip wheel
    install:
    - python -m pip install -r requirements.txt
    - python -m pip install -r cirq/contrib/contrib-requirements.txt
    - python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
    script: check/pytest --benchmark-skip --actually-quiet

  - os: linux
    env: NAME=doctest
    python: "3.6"
    install:
      - pip install -r requirements.txt
      - pip install -r cirq/contrib/contrib-requirements.txt
    script: check/doctest -q
